### PR TITLE
Build succeeds on Lion, Shoes.app also runs on Snow Leopard!

### LINKED ISSUE #119: Shoes 3.0 not working on OS X 10.7
Just letting you know that Shoes 3.0 crashes on startup on OSX 10.7.
Shoes 2.0 on the other hand doesn't.

### PR DESCRIPTION
**Pull request by wasnotrice**
Changes to the process of copying dependencies to `dist/`. Instead of using `make/darwin/shoes.dylibs` (list of dependencies), I'm using otool to discover the dependencies, then adding them to `dist/` as necessary. This gets around the problem of having some dependencies coming from Homebrew and some from the system--we just copy them all regardless of their family of origin.

I haven't attempted the build on Snow Leopard yet, but give it a shot.

I am also using the system libiconv instead of Homebrew's, which might fix #119 and HH #109

### CODE REVIEW

**Comment by steveklabnik** [comment]
Sweeeeet. Thanks!

**Comment by steveklabnik** [comment]
This is awesome, but I'm getting a LSOpenURLsWithRole() failed for the
application /Users/steveklabnik/src/shoes/Shoes.app with error -10810.
when I try to run the app.

**Comment by wasnotrice** [comment]
Hmm. I think that's the error I got when I had to replace libiconv.
Any more info in Console?

On Aug 19, 2011, at 8:27 AM, steveklabnik
reply@reply.github.com
wrote:

**Comment by steveklabnik** [comment]
https://gist.github.com/1157001

is what I'm getting now. It's also taking FOREVER to start up... hm

**Comment by steveklabnik** [comment]
I lied. I just re-did everything, and it's working for me. Works just fine. And 1.9.2!

**Comment by wasnotrice** [comment]
Sweet!

On Aug 19, 2011, at 10:15 AM, steveklabnik
reply@reply.github.com
wrote:

**Pull request merged**
