### PR TITLE
FORMAT README

### PR DESCRIPTION
**Pull request by ferbass**
Format README with markdown

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'm certainly not opposed to this. I'll pull it in with my next batch.

**Comment by ashbb** [comment]
Looks cool! Thanks. I've merged your great work into my repo (ashbb/shoes) for now. :)

**Comment by steveklabnik** [comment]
I don't know why the pull request was closed, but I just merged this into master.

**Comment by ferbass** [comment]
Thks

**Comment by steveklabnik** [comment]
No problem.

**Pull request closed without merging**
