### PR TITLE
remove useless/buggy Encoding code

### PR DESCRIPTION
**Pull request by gderosa**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This breaks my build. I do want to get rid of this, but it's not useless.

**Comment by steveklabnik** [comment]
So, yeah, I'd like to do this. The thing is, on the Mac at least, removing this code causes shoes to crash, with a reference to `unknown class Encoding::UTF_7` or some such. I can get an exact error later.

**Comment by gderosa** [comment]
My ruby is 1.9.2p0 ... yours?

**Comment by steveklabnik** [comment]
1.9.2-p180, iirc. I'm not by my computer at the moment.

This may also be a Mac/Linux issue.

**Comment by gderosa** [comment]
Mmm, so you need to create "dummy" encodings to "make your standard library happy" or something...

In your system, what's the result of 

```
Encoding.list.select{|x| x.dummy?}
```

?

**Comment by steveklabnik** [comment]
Yes, basically.

I'm not sure. Ill try to check into it tonight, but it might take me a day
or two.

**Comment by steveklabnik** [comment]
I plan on getting you a real error this evening.

**Comment by steveklabnik** [comment]
Hey, I'm finally merging this. there's no reason it should be there. :)

Thanks! Sorry it took me ages!

**Pull request merged**
