### PR TITLE
fixed the equality for the spaceship operator

### LINKED ISSUE #175: == is broken for Colors
Run the following script in shows:

```
Shoes.app do
  c1 = rgb 255, 120, 0
  c2 = rgb 0, 255, 120

  if c1 == c2
    alert "Same!!!" 
  else
    alert "Different!!!"
  end
end
```

It will claim that the 2 colors are the same although they are not :-/ It seems that shoes only checks for the presence of all the values and not whether or not they are in the right order (e.g. assigned to red or blue). 

Unfortunately I failed to find the right place for this in the source (and fear that it is in C ;-)  ) - however if someone points me to the right place I'd try to fix it myself :-)

cheers,
Tobi

### PR DESCRIPTION
**Pull request by PragTob**
This shall fix #175 .

About the many loc changed, I really only changed 1857 till 1866 - the others were changed by my editor (automatically removing trailing whitespaces) - if this is a problem I'll happily deactivate the plugin and submit a new pull request. The build works (at least on my machine) and as I'm not really a C-guy I didn't write tests however I used the following short shoes script as a little tests whether it works or not:

```
Shoes.app do
  c1 = rgb 255, 120, 0
  c2 = rgb 0, 255, 120
  c3 = rgb 255, 120, 0
  c4 = rgb 20, 20, 20

  stack do
    if c1 == c2
      para "c1 == c2 (undesired behaviour)"
    else
      para "c1 != c2 (desired behaviour)"
    end

    if c1 == c3
      para "c1 == c3 (desired behaviour)"
    else
      para "c1 != c3 (undesired behaviour)"
    end

    if c1 > c4
      para "c1 > c4 (desired behaviour)"
    else
      para "c1 <= c4 (undesired behaviour)"
    end
  end

end
```

Please let me know if I did something totally wrong. :-)

Cheers,
Tobi

### CODE REVIEW

**Comment by steveklabnik** [comment]
I've been working on a solution to the testing issue, but it's taking some time. I'll be posting to the ML in a few days...

**Comment by PragTob** [comment]
Sounds cool Steve :-)

**Comment by steveklabnik** [comment]
http://librelist.com/browser//shoes/2012/1/4/moving-code-from-c-to-ruby/

**Comment by steveklabnik** [comment]
This looks just fine to me for now. We can get things under test once the testing things shake out. This change is small enough that I have confidence in it for now. We'll want tests later for regressions, though.

**Pull request merged**
